services:
  - type: web
    name: breast-cancer-prediction
    runtime: python
    pythonVersion: 3.10.12
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    env: python
